---
name: Kevin Gangi
title: Cloud DevOps Engineer<br>Linux Systems Administrator<br>Systems Engineer
info:
  location: Orlando, FL
  phone: 781-223-8156
  email: kevin.resume@gangi-home.us
  linkedin: https://linkedin.com/in/kevingangi
  github: https://github.com/phrreakk
  resume: /resume-builder/resume.pdf
projects:
  - link: https://github.com/phrreakk/cybersecurity
    about: Cyber Security Repository
  # - link:
  #   about: